/*
 * Translatable strings file generated by get_titles.pl.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */
gchar *s = N_("The Ziggurat")
  gchar * s = N_("Four Bridges")
  gchar * s = N_("Cloud")
  gchar * s = N_("Tic-Tac-Toe")
  gchar * s = N_("Red Dragon")
  gchar * s = N_("Pyramid's Walls")
  gchar * s = N_("Confounding Cross")
  gchar * s = N_("Difficult")
