#!/bin/sh
#Normalize a postscript file to a file accessible to dvips.
while [ $# -gt 0 ]; do
	ps="temp9999.ps"
	echo "%begin(plot)" > $ps
	cat $1 | \
		sed -e "s#^%begin(plot)#%%%begin(plot)#g" \
		    -e "s#^%end(plot)#%%%end(plot)#g"     \
		    -e "s#^showpage#%showpage#g" >> $ps
	echo "%end(plot)" >> $ps
	shift
done
cat $ps
rm -rf $ps

